### PR TITLE
add xcode template

### PR DESCRIPTION
**Pull request by gre4ixin**
Added template to avoid writing a lot of boilerplate code

### CODE REVIEW

**Comment by devxoul** [comment]
Thanks for your work but I'm worried about this to be included in the official repository. Actually I have some snippets that is used in my company, so how about maintaining those templates in the independent repository? I can feature that repository in the README.md.

**Comment by gre4ixin** [comment]
@devxoul I can create a separate repository for Xcode templates

**Comment by gre4ixin** [comment]
i'm created repository with xcode template
[ReactorKit template](https://github.com/gre4ixin/ReactorKit-Template)

**Comment by gre4ixin** [comment]
I am writing an article for a Russian audience of programmers about rxswift and paid attention to your architecture, when I finish, can you make a code review of my examples?)

**Comment by devxoul** [comment]
@gre4ixin sorry for late reply. Of course I can. Please don't hesitate requesting me a code review on ReactorKit stuff :)

**Comment by devxoul** [comment]
@gre4ixin Sure! I have my email address on my GitHub profile page.

**Comment by devxoul** [comment]
@gre4ixin Sure! I have my email address on my GitHub profile page.

**Comment by gre4ixin** [comment]
can you add link to my repository with template in your repository?)
https://github.com/gre4ixin/ReactorKit-Template

**Comment by devxoul** [comment]
@gre4ixin Done! f12ab114708a2beb17063c5c3b6be81413a71e26

**Pull request closed without merging**
