### PR TITLE
修复实现StoryboardView协议，提前bind导致的Crash

### PR DESCRIPTION
**Pull request by minchaozhang**
Fix crash, because the SubViewController maybe inherit a BaseViewController, all the UI not initialization

### CODE REVIEW

**Comment by minchaozhang** [comment]
AnViewController=>BaseViewController(override viewDidLoad)=>UIViewController

bind方法会先于AnViewController的viewDidLoad执行

**Comment by devxoul** [comment]
@minchaozhang, How can I reproduce the bug? Can you share a sample project?

**Comment by PierreBrisorgueil** [comment]
Hello @devxoul, I think I have come across this concern in a way, and it is maybe related to : https://github.com/ReactorKit/ReactorKit/issues/57

**to reproduce :** 

- Clone your todo example 
- Add a second TaskEditTwoViewController.swift file and a storyboard associated 

for storyboard : init view controller, link custom class to TaskEditTwoViewController, add a textfield linked to titleInput IBOulet

for controller : something like this
```swift
/**
 * Dependencies
 */

import UIKit
import ReactorKit

/**
 * Controller
 */

final class TaskEditTwoViewController: BaseViewController, StoryboardView {
    
    // MARK: UI
    
    @IBOutlet var titleInput: UITextField!
    
    // MARK: Properties
    
    let cancelButtonItem = UIBarButtonItem(barButtonSystemItem: .cancel, target: nil, action: nil)
    let doneButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: nil, action: nil)
    
    // MARK: Initializing
    
    // MARK: Initializing
    
    init(reactor: TaskEditViewReactor) {
        super.init()
        self.navigationItem.leftBarButtonItem = self.cancelButtonItem
        self.navigationItem.rightBarButtonItem = self.doneButtonItem
        self.reactor = reactor
    }
    
    required convenience init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    
    // MARK: View Life Cycle

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Binding
    
    func bind(reactor: TaskEditViewReactor) {
        bindAction(reactor)
        bindState(reactor)
        bindView(reactor)
    }
}

/**
 * Extensions
 */

private extension TaskEditTwoController {
    
    // MARK: views (View -> View)
    
    func bindView(_ reactor: TaskEditViewReactor) {
        // cancel
        self.cancelButtonItem.rx.tap
            .subscribe(onNext: { [weak self] _ in
                guard let `self` = self else { return }
                self.dismiss(animated: true, completion: nil)
            })
            .disposed(by: self.disposeBag)
    }
    
    // MARK: actions (View -> Reactor)
    
    func bindAction(_ reactor: TaskEditViewReactor) {
        self.doneButtonItem.rx.tap
            .map { Reactor.Action.submit }
            .bind(to: reactor.action)
            .disposed(by: self.disposeBag)
        
        self.titleInput.rx.text
            .filterNil()
            .map(Reactor.Action.updateTaskTitle)
            .bind(to: reactor.action)
            .disposed(by: self.disposeBag)
    }
    
    // MARK: states (Reactor -> View)
    
    func bindState(_ reactor: TaskEditViewReactor) {
        reactor.state.asObservable().map { $0.title }
            .distinctUntilChanged()
            .bind(to: self.titleInput.rx.text)
            .disposed(by: self.disposeBag)
    }
}
```

- change action of TaskListViewController  in order to launch the new controller : 

```swift
    self.addButtonItem.rx.tap
      .map(reactor.reactorForCreatingTask)
      .subscribe(onNext: { [weak self] reactor in
        guard let `self` = self else { return }
        let viewController = TaskEditTwoController(reactor: reactor)
        let navigationController = UINavigationController(rootViewController: viewController)
        self.present(navigationController, animated: true, completion: nil)
      })
      .disposed(by: self.disposeBag)
```

you will have a crash : Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value, Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

I'm really new on swift but maybe it's this bug :

"Fix crash, because the SubViewController maybe inherit a BaseViewController, all the UI not initialization" => "Fix crash, because the TaskEditTwoViewController inherit a BaseViewController, but the UI is not instantiate"

I think I have the same problem on my side, maybe related at the mp I sent you on slack. I do not understand why but my code works, if I inject it into your example of Todo, the only difference that has my stack is based on storyboard so I instantiated my sotryboard via RxFlow differently, which could explain the break of tranforms. I continue to try to dig the subject, available on slack if necessary, if you want my branch or whatever.

**Comment by devxoul** [comment]
Hmm, I don't think this fixes the problem. Using Storyboard, you should never initialize the view controller directly. You may replace the code with:

```diff
- let viewController = TaskEditTwoController(reactor: reactor)
+ let viewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "TaskEditTwo") as! TaskEditTwoViewController
+ viewController.reactor = reactor
```

**Pull request merged**
