### PR TITLE
Migrate to RxRelay

### PR DESCRIPTION
**Pull request by MortyMerr**
This PR is blocked by https://github.com/devxoul/RxExpect/pull/16
This PR closes https://github.com/ReactorKit/ReactorKit/issues/103
This PR closes https://github.com/ReactorKit/ReactorKit/issues/62

### CODE REVIEW

**Comment by devxoul** [comment]
I think `ActionSubject` can be replaced with `PublishRelay` (with tons of breaking changes 😂) but `StateRelay` cannot since it breaks a convenient syntax of stub value:

https://github.com/ReactorKit/ReactorKit/pull/104#issuecomment-502337676

**Comment by MortyMerr** [comment]
Hey @devxoul thank you for the comment!
I can revert `StateRelay` changes if it's necessary :)

But IMO `Variable` and "assign new value to emit new event" syntax was deprecated because of rational reasons. It doesn't correspond with ReactiveX guidelines, it's too implicit, it's imperative.

`BehaviorRelay` is a part of RxSwift main repo, so it's much more convenient to use. Users are familiar with official RxSwift types/traits and don't need to look into `ReactorKit` sources trying to understand what `StateRelay` really is. Moreover `StateRelay` has an unfamiliar API for all who use Relay in RxJava/RxSwift.

As for your problem (stub state), I think that accepting a new state is really more explicit, than changing the current. It helps to understand that we can't change the current state, only emit new one. With lense pattern or default `State` init parameters it can be  as short as mutating property:
```swift
reactor.stub.state.accept(.init(age: 20))
```
What do you think?

Sincerely

**Comment by devxoul** [comment]
I totally agree with that `Variable` is against ReactiveX philosophy. I've got some thoughts on the changes:

**ActionSubject**

We don't actually need to expose Subject or Relay directly. I think `AnyObserver` would be the better alternative. 🤔

**StateRelay**

It is only used in the test code so I think it is not that necessary to follow ReactiveX philosophy strictly. Rather that, it would be better to provide some convenient interface so that users can easily manipulate the stub states. A memberwise initializer is not an option because it requires all properties.

```swift
struct State {
  var name: String
  var age: Int
  var gender: Gender
  var address: String
}

// ❌ need to pass name, gender, address as well 
reactor.stub.state.accept(.init(age: 20))

// 🤔🤔🤔
reactor.stub.state.accept(.init(
  name: reactor.stub.state.name,
  age: 20,
  name: reactor.stub.state.gender,
  name: reactor.stub.state.address,
))
```

**Comment by MortyMerr** [comment]
> I think AnyObserver would be the better alternative. 🤔

I don't think `AnyObserver` fits well here, cause it lies to a user of that interface. The thing is we can't send `.completed` or `.error` event to actions. So they will be just ignored under the hood. So what's the point to provide such API? We can only accept new element (`Action`). `PublishRelay` fits perfect for that.

> It is only used in the test code so I think it is not that necessary to follow ReactiveX philosophy 

Well, again, I respect your opinion as a creator or that framework and will agree to any option :)
I am glad to see we agree about `Variable`. `StateRelay` looks the same for me. I think that every framework built-in on RxSwift in roots should respect its philosophy and guidelines because they were implemented/discussed by many smart people which I tend to trust. Test code is not less important than application code, it also should be readable and clear.

`State` struct properties usually have their default values (in your examples and in production code). It's just comfortable to init them with initial values. Swift 5 memberwise constructor now supports default parameters - https://github.com/apple/swift/pull/19743
So, your example can be implemented like that:
```swift
struct State {
  var name = ""
  var age = 0
  var gender: Gender = .male
  var address: String = ""
}

reactor.stub.state.accept(.init(age: 20)) // memberwise supports default values
reactor.stub.state.accept(.init(adress: "CA"))  // memberwise supports default values
```

If a user doesn't like default values (i can't see any rational reason for that, but maybe he doesn't like) he can rewrite it like this:
```swift
struct State {
  var name = ""
  var age = 0
  var gender: Gender = .male
  var address: String = ""
}

var stubState = State(name: "", age: 10, gender: .male, adress: "")
stubState.age = 20
reactor.stub.state.accept(stubState)
stubState.adress = "CA"
reactor.stub.state.accept(stubState) 
```
I think that these two options provides fully comfortable API without going against RxSwift guidelines.

**Pull request closed without merging**
