### PR TITLE
Support RxSwift 5.0

### PR DESCRIPTION
**Pull request by mariohahn**
Support RxSwift 5.0
Support RxCocoa 5.0

Fix Examples

### CODE REVIEW

**Comment by mariohahn** [comment]
https://github.com/ReactorKit/ReactorKit/issues/101

**Comment by ZuluTradeMobile** [comment]
Thanks for your work, I'd also love to see that merged since it's holding us back. @devxoul could you please have a look?

**Comment by phi161** [comment]
I'd also love to see that merged - @devxoul could you please have a look?

**Comment by farhatmo** [comment]
Many of us are waiting this PR. @devxoul can you help ?

**Comment by devxoul** [comment]
@mariohahn Thanks  for your contribution but actually I have had a working branch for RxSwift 5 since March. I have just released [ReactorKit 2.0.0](https://github.com/ReactorKit/ReactorKit/releases/tag/2.0.0) which support Swift 5 and RxSwift 5 :tada:

**Pull request closed without merging**
